name: Stock Data Collection

on:
  schedule:
    # Run Monday-Friday at 4:30 PM EST (after market close)
    # GitHub Actions uses UTC time, so 21:30 UTC = 4:30 PM EST
    - cron: '30 21 * * 1-5'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  collect-stock-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run stock data collection
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python main.py
